name: Bug report
description: Create a report to help us improve stability
labels: [bug]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Short description of the defect.
      placeholder: Vitality orb freezes on iPad
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide clear steps (include URLs, accounts, data).
      placeholder: |
        1. Go to ...
        2. Tap ...
        3. Observe ...
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: Orb should continue rotating after sync completes.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: Describe what actually happens, include screenshots if possible.
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: e.g. iPadOS 18.1 / Safari, staging.fitfluid.app
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Additional context / logs
      description: Paste relevant console logs, screenshots, or links to failing builds.
    validations:
      required: false
